// Single copy catalog for both prototype directions.
// zh and en carry identical keys; the visual direction renders the same
// messages as glyphs/scenes and keeps these strings for tooltip and aria.
window.SCREENER_COPY = {
  zh: {
    "brand.name": "Screener",
    "brand.home": "Screener 首页",

    "common.roomCode": "房间号",
    "common.copy": "复制",
    "common.copied": "已复制",
    "common.copyFailed": "复制失败",
    "common.cancel": "取消",
    "common.confirm": "确认",
    "common.retry": "重试",
    "common.refresh": "刷新页面",
    "common.save": "保存",
    "common.edit": "编辑",
    "common.or": "或",
    "common.viewers": "观看者",
    "common.online": "在线",
    "common.you": "你",
    "common.host": "分享者",
    "common.close": "收起",

    "gate.title": "站点访问",
    "gate.hint": "请输入站点口令",
    "gate.password": "站点口令",
    "gate.submit": "进入站点",
    "gate.checking": "正在验证站点访问",
    "gate.wrong": "站点口令不正确，请重试",
    "gate.unavailable": "暂时无法验证站点访问",

    "join.title": "加入房间",
    "join.hint": "输入分享者发来的四位房间号",
    "join.field": "房间号",
    "join.submit": "加入",
    "join.invalid": "请输入 1000 至 9999 的四位房间号",
    "join.joining": "正在加入房间",
    "join.notFound": "房间不存在或已过期",
    "join.notFoundHint": "请确认房间号，或向分享者获取新的邀请链接。",
    "join.denied": "当前无法通过房间号加入",
    "join.deniedHint": "请使用分享者提供的邀请链接，或尝试房间密码。",
    "join.password": "房间密码",
    "join.passwordHint": "请输入 1-32 个可见字符",
    "join.passwordError": "无法加入房间，请检查密码后重试",
    "join.passwordAction": "输入房间密码",
    "join.full": "房间已满",
    "join.fullHint": "一个房间最多 20 位观看者，请稍后再试。",

    "host.title": "{name} 的屏幕",
    "host.titleFallback": "我的屏幕",
    "host.idle.heading": "想播点什么？",
    "host.idle.hint": "分享你的屏幕，朋友凭房间号或邀请链接就能进来看。",
    "host.start": "开始分享",
    "host.join": "加入房间",
    "host.starting": "正在连接",
    "host.cancelStart": "取消",
    "host.live": "正在分享",
    "host.paused": "已暂停",
    "host.ended": "已停止分享",
    "host.roomReady": "房间已就绪",
    "host.pause": "暂停分享",
    "host.resume": "恢复分享",
    "host.switchSource": "切换来源",
    "host.switching": "正在选择",
    "host.stop": "停止分享",
    "host.noAudio": "当前来源没有可共享音频",
    "host.localPreviewPaused": "本地预览已暂停，分享仍在继续",
    "host.pauseNotice": "音视频分享已暂停",
    "host.resumeNotice": "音视频分享已恢复",
    "host.stopNotice": "已停止分享",
    "host.roomReplaced": "房间号已更换",
    "host.roomInvalid": "房间已失效，再次点击将创建新房",
    "host.roomReplace": "更换房间号",
    "host.roomReplaceConfirm": "确认更换房间号",
    "host.captureError": "无法开始屏幕采集，请检查浏览器权限后重试",

    "host.name": "昵称",
    "host.nameSave": "保存昵称",
    "host.nameCancel": "取消编辑昵称",
    "host.nameEdit": "编辑昵称",
    "host.nameError": "名称格式无效或超过 24 个字符",

    "host.invite": "邀请链接",
    "host.invite.ready": "可用",
    "host.invite.none": "暂无",
    "host.invite.copy": "复制邀请链接",
    "host.invite.rotate": "更新邀请链接",
    "host.invite.revoke": "撤销邀请链接",
    "host.invite.rotateShort": "更新链接",
    "host.invite.revokeShort": "撤销链接",
    "host.invite.updated": "邀请链接已更新",
    "host.invite.revoked": "邀请链接已撤销",
    "host.invite.emptyOpen": "暂无邀请链接，仍可凭房间号加入",
    "host.invite.emptyPassword": "暂无邀请链接，仍可凭房间号和密码加入",
    "host.invite.emptyPrivate": "暂无邀请链接，请先更新链接再邀请他人",

    "host.policy": "准入方式",
    "host.policy.open": "公开",
    "host.policy.private": "私密",
    "host.policy.openHint": "知道房间号即可加入",
    "host.policy.privateHint": "凭邀请链接加入，或设置房间密码",
    "host.password.set": "房间密码已设置",
    "host.password.unset": "房间密码未设置",
    "host.password.placeholder": "设置后可凭房间号加入",
    "host.password.setAction": "设置房间密码",
    "host.password.changeAction": "更改房间密码",
    "host.password.remove": "移除房间密码",
    "host.password.show": "显示房间密码",
    "host.password.hide": "隐藏房间密码",
    "host.password.saved": "房间密码已设置",
    "host.password.updated": "房间密码已更新",
    "host.password.removed": "房间密码已移除，仅限邀请加入",

    "host.viewers.empty": "暂无观看者",
    "host.viewers.waiting": "等待朋友加入",

    "host.quality": "视频预设",
    "host.quality.720p30": "720p · 30 帧",
    "host.quality.1080p30": "1080p · 30 帧",
    "host.quality.1080p60": "1080p · 60 帧",
    "host.advanced": "高级设置",
    "host.advanced.resolution": "分辨率上限",
    "host.advanced.framerate": "帧率上限",
    "host.advanced.bitrate": "视频码率上限",
    "host.advanced.preference": "画面偏好",
    "host.advanced.preference.resolution": "清晰",
    "host.advanced.preference.balanced": "均衡",
    "host.advanced.preference.framerate": "流畅",
    "host.advanced.preference.resolutionHint": "保留细节",
    "host.advanced.preference.balancedHint": "自动权衡",
    "host.advanced.preference.framerateHint": "优先帧率",
    "host.advanced.audio": "音频质量",
    "host.advanced.audio.saver": "普通",
    "host.advanced.audio.music": "音乐",
    "host.advanced.audio.veryHigh": "保真",
    "host.advanced.route": "路由策略",
    "host.advanced.route.topo": "自动优化拓扑",
    "host.advanced.route.topoHint": "观看中逐步选择更健康的连接",
    "host.advanced.route.peerOnly": "纯 P2P",
    "host.advanced.route.peerOnlyHint": "不使用媒体服务器，无法直连时停止尝试",
    "host.advanced.codec": "视频编码",
    "host.advanced.codec.auto": "自动",
    "host.advanced.codec.autoHint": "自动选择",
    "host.advanced.codec.vp8Hint": "兼容优先",
    "host.advanced.codec.h264Hint": "硬件优先",

    "host.details": "显示连接详情",
    "host.details.hide": "隐藏连接详情",
    "host.topology": "连接拓扑",
    "host.topology.show": "显示连接拓扑",
    "host.topology.hide": "隐藏连接拓扑",
    "host.topology.pending": "连接中",
    "host.sfu": "媒体服务器",

    "state.signal.connected": "服务器已连接",
    "state.signal.connecting": "正在连接",
    "state.signal.reconnecting": "正在恢复",
    "state.signal.offline": "服务器未连接",
    "state.peer.connected": "已连接",
    "state.peer.connecting": "正在连接",
    "state.peer.routing": "正在分配线路",
    "state.peer.waiting": "等待开始分享",
    "state.peer.reconnecting": "正在恢复",
    "state.peer.failed": "连接失败",
    "state.route.p2p": "P2P 直连",
    "state.route.sfu": "服务器中转",

    "stats.title": "连接数据",
    "stats.relay": "转发数据",
    "stats.downstream": "下游接收数据",
    "stats.more": "详细指标",
    "stats.resolution": "分辨率",
    "stats.fps": "帧率",
    "stats.bitrate": "码率",
    "stats.loss": "丢包率",
    "stats.rtt": "RTT",
    "stats.codec": "视频编码",
    "stats.jitter": "网络抖动",
    "stats.dropped": "丢帧",
    "stats.encoder": "编码器",
    "stats.audio": "音频码率",
    "stats.unknown": "未知",

    "viewer.title": "{name} 的屏幕",
    "viewer.titleFallback": "好友屏幕",
    "viewer.reconnect": "重新连接媒体",
    "viewer.play": "点击播放",

    "viewer.msg.joining": "正在加入房间",
    "viewer.msg.waitingHost": "等待开始分享",
    "viewer.msg.preparingP2p": "正在建立 P2P",
    "viewer.msg.preparingSfu": "正在连接备用线路",
    "viewer.msg.allocating": "正在分配线路",
    "viewer.msg.receiving": "正在接收画面",
    "viewer.msg.playing": "正在播放",
    "viewer.msg.needsPlay": "点击播放",
    "viewer.msg.hostPaused": "分享者已暂停",
    "viewer.msg.recovering": "正在恢复连接",
    "viewer.msg.routeFailed": "没有可用的媒体线路",
    "viewer.msg.playbackFailed": "浏览器无法播放当前画面",
    "viewer.msg.hostOffline": "分享者连接已中断",
    "viewer.msg.serverError": "连接服务暂时不可用",
    "viewer.msg.notFound": "房间不存在或已过期",
    "viewer.msg.denied": "当前无法通过房间号加入",
    "viewer.msg.invalidInvite": "邀请链接无效或已失效",
    "viewer.msg.expired": "房间已过期",
    "viewer.msg.closed": "房间已关闭",
    "viewer.msg.full": "当前无法加入房间",
    "viewer.msg.stale": "页面版本已更新，请刷新后重试",

    "viewer.notice.signalRecovering": "服务器连接正在恢复，画面仍在播放",
    "viewer.notice.mediaRecovering": "媒体连接正在恢复",
    "viewer.notice.hostOffline": "分享者连接已中断，画面可能冻结",

    "viewer.hint.denied": "请使用分享者提供的邀请链接，或尝试房间密码。",
    "viewer.hint.notFound": "请确认房间号，或向分享者获取新的邀请链接。",
    "viewer.hint.invite": "请向分享者获取新的邀请链接。",
    "viewer.hint.generic": "请检查入口后重试。",

    "mode.language": "界面语言",
    "mode.zh": "中文",
    "mode.en": "English",
    "mode.vis": "纯视觉",

    "theme.dark": "切换到暗色模式",
    "theme.light": "切换到浅色模式",
    "theme.dark.short": "暗色",
    "theme.light.short": "浅色",

    "story.room": "找到房间",
    "story.link": "建立连接",
    "story.show": "接收画面",
  },

  en: {
    "brand.name": "Screener",
    "brand.home": "Screener home",

    "common.roomCode": "Room code",
    "common.copy": "Copy",
    "common.copied": "Copied",
    "common.copyFailed": "Copy failed",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.retry": "Retry",
    "common.refresh": "Refresh page",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.or": "or",
    "common.viewers": "Viewers",
    "common.online": "online",
    "common.you": "You",
    "common.host": "Host",
    "common.close": "Close",

    "gate.title": "Site access",
    "gate.hint": "Enter the site passphrase",
    "gate.password": "Site passphrase",
    "gate.submit": "Enter site",
    "gate.checking": "Checking site access",
    "gate.wrong": "Incorrect passphrase, try again",
    "gate.unavailable": "Site access cannot be verified right now",

    "join.title": "Join a room",
    "join.hint": "Enter the four-digit room code from your friend",
    "join.field": "Room code",
    "join.submit": "Join",
    "join.invalid": "Enter a four-digit room code between 1000 and 9999",
    "join.joining": "Joining the room",
    "join.notFound": "Room not found or expired",
    "join.notFoundHint": "Check the room code, or ask the host for a new invite link.",
    "join.denied": "This room cannot be joined by code right now",
    "join.deniedHint": "Use the host's invite link, or try the room password.",
    "join.password": "Room password",
    "join.passwordHint": "1-32 visible characters",
    "join.passwordError": "Could not join; check the password and try again",
    "join.passwordAction": "Enter room password",
    "join.full": "Room is full",
    "join.fullHint": "A room holds at most 20 viewers. Try again later.",

    "host.title": "{name}'s screen",
    "host.titleFallback": "My screen",
    "host.idle.heading": "Something worth watching?",
    "host.idle.hint": "Share your screen and friends can drop in with the room code or invite link.",
    "host.start": "Start sharing",
    "host.join": "Join a room",
    "host.starting": "Connecting",
    "host.cancelStart": "Cancel",
    "host.live": "Live",
    "host.paused": "Paused",
    "host.ended": "Sharing stopped",
    "host.roomReady": "Room ready",
    "host.pause": "Pause sharing",
    "host.resume": "Resume sharing",
    "host.switchSource": "Switch source",
    "host.switching": "Choosing",
    "host.stop": "Stop sharing",
    "host.noAudio": "This source has no shareable audio",
    "host.localPreviewPaused": "Local preview paused; sharing continues",
    "host.pauseNotice": "Audio and video sharing paused",
    "host.resumeNotice": "Audio and video sharing resumed",
    "host.stopNotice": "Sharing stopped",
    "host.roomReplaced": "Room code replaced",
    "host.roomInvalid": "Room expired; press again to create a new one",
    "host.roomReplace": "Replace room code",
    "host.roomReplaceConfirm": "Confirm replacing the room code",
    "host.captureError": "Screen capture unavailable; check browser permission and retry",

    "host.name": "Display name",
    "host.nameSave": "Save display name",
    "host.nameCancel": "Cancel editing",
    "host.nameEdit": "Edit display name",
    "host.nameError": "Invalid name, or longer than 24 characters",

    "host.invite": "Invite link",
    "host.invite.ready": "Ready",
    "host.invite.none": "None",
    "host.invite.copy": "Copy invite link",
    "host.invite.rotate": "Rotate invite link",
    "host.invite.revoke": "Revoke invite link",
    "host.invite.rotateShort": "Rotate link",
    "host.invite.revokeShort": "Revoke link",
    "host.invite.updated": "Invite link rotated",
    "host.invite.revoked": "Invite link revoked",
    "host.invite.emptyOpen": "No invite link; the room code still works",
    "host.invite.emptyPassword": "No invite link; room code plus password still works",
    "host.invite.emptyPrivate": "No invite link; rotate one before inviting",

    "host.policy": "Admission",
    "host.policy.open": "Open",
    "host.policy.private": "Private",
    "host.policy.openHint": "Anyone with the room code can join",
    "host.policy.privateHint": "Invite link only, or set a room password",
    "host.password.set": "Room password set",
    "host.password.unset": "No room password",
    "host.password.placeholder": "Set one to allow code entry",
    "host.password.setAction": "Set room password",
    "host.password.changeAction": "Change room password",
    "host.password.remove": "Remove room password",
    "host.password.show": "Show room password",
    "host.password.hide": "Hide room password",
    "host.password.saved": "Room password set",
    "host.password.updated": "Room password updated",
    "host.password.removed": "Password removed; invite link only",

    "host.viewers.empty": "No viewers yet",
    "host.viewers.waiting": "Waiting for friends to join",

    "host.quality": "Video preset",
    "host.quality.720p30": "720p · 30 fps",
    "host.quality.1080p30": "1080p · 30 fps",
    "host.quality.1080p60": "1080p · 60 fps",
    "host.advanced": "Advanced settings",
    "host.advanced.resolution": "Resolution ceiling",
    "host.advanced.framerate": "Frame rate ceiling",
    "host.advanced.bitrate": "Video bitrate ceiling",
    "host.advanced.preference": "Picture preference",
    "host.advanced.preference.resolution": "Clarity",
    "host.advanced.preference.balanced": "Balanced",
    "host.advanced.preference.framerate": "Fluency",
    "host.advanced.preference.resolutionHint": "Keep detail",
    "host.advanced.preference.balancedHint": "Weigh automatically",
    "host.advanced.preference.framerateHint": "Prefer frame rate",
    "host.advanced.audio": "Audio quality",
    "host.advanced.audio.saver": "Standard",
    "host.advanced.audio.music": "Music",
    "host.advanced.audio.veryHigh": "Lossless-ish",
    "host.advanced.route": "Route policy",
    "host.advanced.route.topo": "Auto topology tuning",
    "host.advanced.route.topoHint": "Gradually pick healthier paths while live",
    "host.advanced.route.peerOnly": "Pure P2P",
    "host.advanced.route.peerOnlyHint": "No media server; stop when direct paths fail",
    "host.advanced.codec": "Video codec",
    "host.advanced.codec.auto": "Auto",
    "host.advanced.codec.autoHint": "Pick automatically",
    "host.advanced.codec.vp8Hint": "Compatibility first",
    "host.advanced.codec.h264Hint": "Hardware first",

    "host.details": "Show connection details",
    "host.details.hide": "Hide connection details",
    "host.topology": "Connection topology",
    "host.topology.show": "Show connection topology",
    "host.topology.hide": "Hide connection topology",
    "host.topology.pending": "Connecting",
    "host.sfu": "Media server",

    "state.signal.connected": "Server connected",
    "state.signal.connecting": "Connecting",
    "state.signal.reconnecting": "Recovering",
    "state.signal.offline": "Server offline",
    "state.peer.connected": "Connected",
    "state.peer.connecting": "Connecting",
    "state.peer.routing": "Routing",
    "state.peer.waiting": "Waiting for share",
    "state.peer.reconnecting": "Recovering",
    "state.peer.failed": "Connection failed",
    "state.route.p2p": "P2P direct",
    "state.route.sfu": "Via server",

    "stats.title": "Connection data",
    "stats.relay": "Relay data",
    "stats.downstream": "Downstream receive data",
    "stats.more": "Detailed metrics",
    "stats.resolution": "Resolution",
    "stats.fps": "Frame rate",
    "stats.bitrate": "Bitrate",
    "stats.loss": "Packet loss",
    "stats.rtt": "RTT",
    "stats.codec": "Video codec",
    "stats.jitter": "Jitter",
    "stats.dropped": "Dropped frames",
    "stats.encoder": "Encoder",
    "stats.audio": "Audio bitrate",
    "stats.unknown": "Unknown",

    "viewer.title": "{name}'s screen",
    "viewer.titleFallback": "A friend's screen",
    "viewer.reconnect": "Reconnect media",
    "viewer.play": "Tap to play",

    "viewer.msg.joining": "Joining the room",
    "viewer.msg.waitingHost": "Waiting for the host to share",
    "viewer.msg.preparingP2p": "Establishing P2P",
    "viewer.msg.preparingSfu": "Connecting backup route",
    "viewer.msg.allocating": "Allocating a route",
    "viewer.msg.receiving": "Receiving video",
    "viewer.msg.playing": "Playing",
    "viewer.msg.needsPlay": "Tap to play",
    "viewer.msg.hostPaused": "Host paused",
    "viewer.msg.recovering": "Recovering connection",
    "viewer.msg.routeFailed": "No media route available",
    "viewer.msg.playbackFailed": "The browser cannot play this stream",
    "viewer.msg.hostOffline": "Host connection lost",
    "viewer.msg.serverError": "Connection service unavailable",
    "viewer.msg.notFound": "Room not found or expired",
    "viewer.msg.denied": "This room cannot be joined by code right now",
    "viewer.msg.invalidInvite": "Invite link invalid or expired",
    "viewer.msg.expired": "Room expired",
    "viewer.msg.closed": "Room closed",
    "viewer.msg.full": "Cannot join the room right now",
    "viewer.msg.stale": "Page updated; refresh to continue",

    "viewer.notice.signalRecovering": "Server reconnecting; video keeps playing",
    "viewer.notice.mediaRecovering": "Media connection recovering",
    "viewer.notice.hostOffline": "Host connection lost; picture may freeze",

    "viewer.hint.denied": "Use the host's invite link, or try the room password.",
    "viewer.hint.notFound": "Check the room code, or ask the host for a new invite link.",
    "viewer.hint.invite": "Ask the host for a new invite link.",
    "viewer.hint.generic": "Check your entry point and try again.",

    "mode.language": "Interface language",
    "mode.zh": "中文",
    "mode.en": "English",
    "mode.vis": "Visual only",

    "theme.dark": "Switch to dark mode",
    "theme.light": "Switch to light mode",
    "theme.dark.short": "Dark",
    "theme.light.short": "Light",

    "story.room": "Room found",
    "story.link": "Linking up",
    "story.show": "Receiving picture",
  },
};
